const knowledgeBase = {
    timetable: {
      "Monday": [
          "08:45 AM - NoSQL (BCA552)",
          "09:35 AM - NoSQL (BCA552)",
          "10:25 AM - Library (BCA552)",
          "11:15 AM - PROJECT-I (BCA581)",
          "12:05 PM - CYBER SECURITY (BCA542C)",
          "01:45 PM - MOBILE APPLICATIONS (BCA531)",
          "02:35 PM - MOBILE APPLICATIONS (BCA531)",
          "03:25 PM - MOBILE APPLICATIONS (BCA531)"
      ],
      "Tuesday": [
          "08:45 AM - MOBILE APPLICATIONS (BCA581)",
          "09:35 AM - COMPUTER NETWORKS (BCA551)",
          "10:25 AM - Research",
          "11:15 AM - CYBER SECURITY (BCA542C)",
          "12:05 PM - PROJECT-I (BCA581)",
          "01:45 PM - Activity Period"
      ],
      "Wednesday": [
          "08:45 AM - COMPUTER NETWORKS (BCA551)",
          "09:35 AM - CYBER SECURITY (BCA532)",
          "10:25 AM - Research",
          "11:15 AM - Library (BCA552)",
          "12:05 PM - NoSQL (BCA552)",
          "01:45 PM - MOBILE APPLICATIONS (BCA531)",
          "02:35 PM - MOBILE APPLICATIONS (BCA531)",
          "03:25 PM - Cloud Computing"
      ],
      "Thursday": [
          "08:45 AM - NoSQL (BCA552)",
          "09:35 AM - MOBILE APPLICATIONS (BCA531)",
          "10:25 AM - Library",
          "11:15 AM - Mentoring",
          "12:05 PM - PROJECT-I (BCA581)",
          "01:45 PM - Placement",
          "02:35 PM - COMPUTER NETWORKS (BCA551)",
          "03:25 PM - CYBER SECURITY (BCA542C)"
      ],
      "Friday": [
          "08:45 AM - COMPUTER NETWORKS (BCA551)",
          "09:35 AM - CYBER SECURITY (BCA532)",
          "10:25 AM - Research",
          "11:15 AM - Library (BCA552)",
          "12:05 PM - NoSQL (BCA552)",
          "01:45 PM - MOBILE APPLICATIONS (BCA531)",
          "02:35 PM - MOBILE APPLICATIONS (BCA531)",
          "03:25 PM - Machine Learning"
      ],
      "Saturday": [
          "08:45 AM - COMPUTER NETWORKS (BCA551)",
          "09:35 AM - CYBER SECURITY (BCA532)",
          "10:25 AM - Research",
          "11:15 AM - NoSQL (BCA552)",
      ]
  },
  teachers: [
    { name: "ABHILASHA", email: "abhilasha@res.christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "" },
    { name: "ABHINAV SINGHAL", email: "abhinav.singhal@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A 2016H, SECOND FLOOR, A - BLOCK" },
    { name: "AMRIT KAUR SAGGU", email: "amrit.kaur@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A-216-L, SECOND FLOOR, A - BLOCK" },
    { name: "ANSA MATHEW", email: "mathew.ansa@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "216-B, SECOND FLOOR, A - BLOCK" },
    { name: "ASHISH SHARMA", email: "ashish.sharma@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A206-G, SECOND FLOOR, A - BLOCK" },
    { name: "BOSCO PAUL ALAPATT", email: "bosco.paul@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "206/F/ SCHOOL OF SCIENCES, SECOND FLOOR, A - BLOCK" },
    { name: "GARIMA ANAND", email: "garima.anand@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A 206-E, SECOND FLOOR, A - BLOCK" },
    { name: "GLORY C", email: "c.glory@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "" },
    { name: "INDU VERMA", email: "indu.verma@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A216G, SECOND FLOOR, A - BLOCK" },
    { name: "JASPREET SINGH", email: "jaspreet.singh@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "" },
    { name: "JOSSY P GEORGE", email: "frjossy@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "Director Office, GROUND FLOOR, B - BLOCK" },
    { name: "KAMAL UPRETI", email: "kamal.upreti@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A216-I, SECOND FLOOR, A - BLOCK" },
    { name: "KULJEET SINGH", email: "kuljeet.singh@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "" },
    { name: "LATA YADAV", email: "lata.yadav@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "B501A, FIFTH FLOOR, B - BLOCK" },
    { name: "LAWRENCE KUJUR", email: "lawrence.kujur@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A216-K, SECOND FLOOR, A - BLOCK" },
    { name: "MADAN SINGH", email: "madan.singh@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "517C, FIFTH FLOOR, A - BLOCK" },
    { name: "MANJULA SHANBHOG", email: "manjula.shanbhog@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A 216-H, SECOND FLOOR, A - BLOCK" },
    { name: "MEGHAVI RANA", email: "meghavi.rana@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "" },
    { name: "MUDITA SHARAN", email: "mudita.sharan@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "FIFTH FLOOR, A - BLOCK" },
    { name: "NEHA SAINI", email: "neha.saini@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A-521, FIFTH FLOOR, A - BLOCK" },
    { name: "PRASHANT KHILERI", email: "", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "Scholar's Room, FOURTH FLOOR, A - BLOCK" },
    { name: "PRATEEK SINGHAL", email: "prateek.singhal@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "" },
    { name: "PREETY", email: "preety@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "B-501D, FIFTH FLOOR, B - BLOCK" },
    { name: "RAJESH GUPTA", email: "rajesh.gupta@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "" },
    { name: "RAMESH CHANDRA POONIA", email: "rameshchandra.poonia@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "216-J, SECOND FLOOR, A - BLOCK" },
    { name: "RIYA BABY", email: "riya.baby@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A-206 C, SECOND FLOOR, A - BLOCK" },
    { name: "SEEMA", email: "seema.seema@res.christuniversity", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "Scholar's room, FOURTH FLOOR, A - BLOCK" },
    { name: "SHILPA SRIVASTAVA", email: "shilpa.srivastava@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A206J, SECOND FLOOR, A - BLOCK" },
    { name: "SHUBHAM MAHAJAN", email: "shubham.mahajan@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "" },
    { name: "SWATI AGRAWAL", email: "swati.agrawal@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A206B, SECOND FLOOR, A - BLOCK" },
    { name: "VANDANA MEHNDIRATTA", email: "vandana.mehndiratta@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A206-A, SECOND FLOOR, A - BLOCK" },
    { name: "VANDANA SHARMA", email: "vandana.sharma@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "501 F, FIFTH FLOOR, B - BLOCK" },
    { name: "VARUNA GUPTA", email: "varuna.gupta@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "A206-D, SECOND FLOOR, A - BLOCK" },
    { name: "VIDUSHI", email: "vidushi@christuniversity.in", department: "SCIENCES (NCR)", campus: "DELHI NCR CAMPUS", location: "512, FIFTH FLOOR, A - BLOCK" },
  ],
  pgandhostel: [],
  clubsandsocieties: [],
  foodoption: [],
  laundry: [],
  gymdetail: [],
  acadmicoffice: [],
  newstudentchecklist: [],
  sportsfacility: [],
  busservices: [],
  facultylocation: [],
  };
  
  export default knowledgeBase;